name: Issue Command

on:
  issue_comment:
    types: [created]

jobs:
  rebase:
    name: Automatic Rebase
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase') && github.event.comment.author_association == 'COLLABORATOR'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  self-assign:
    name: Self Assign
    if: ${{ !github.event.issue.pull_request && startsWith(github.event.comment.body, '/wip') }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      issues: write
    steps:
      - uses: bdougie/take-action@v1.6.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          trigger: '/wip'

  test-on-demand:
    name: Test route on demand
    if: startsWith(github.event.comment.body, '/test')
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      issues: write
      attestations: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if comment is on a pull request
        id: check-pr
        uses: actions/github-script@v7
        with:
          script: |
            const isPullRequest = !!context.payload.issue.pull_request;
            core.setOutput('is_pr', isPullRequest);
            return isPullRequest;

      - name: Install pnpm (for non-PR)
        if: steps.check-pr.outputs.is_pr == 'false'
        uses: pnpm/action-setup@v4

      - name: Use Node.js Active LTS (for non-PR)
        if: steps.check-pr.outputs.is_pr == 'false'
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: Install dependencies (for non-PR)
        if: steps.check-pr.outputs.is_pr == 'false'
        run: pnpm i && pnpm rb

      - name: Fetch PR data (for PR)
        if: steps.check-pr.outputs.is_pr == 'true'
        uses: octokit/request-action@v2.x
        id: pr-data
        with:
          route: GET /repos/{repo}/pulls/{number}
          repo: ${{ github.repository }}
          number: ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch Docker image (for PR)
        if: steps.check-pr.outputs.is_pr == 'true'
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: docker-test.yml
          name: docker-image
          path: ../artifacts-${{ github.run_id }}

      - name: Import Docker image and set up Docker container (for PR)
        if: steps.check-pr.outputs.is_pr == 'true'
        working-directory: ../artifacts-${{ github.run_id }}
        run: |
          set -ex
          zstd -d --stdout rsshub.tar.zst | docker load
          docker run -d \
            --name rsshub \
            -e NODE_ENV=dev \
            -e LOGGER_LEVEL=debug \
            -e ALLOW_USER_HOTLINK_TEMPLATE=true \
            -e ALLOW_USER_SUPPLY_UNSAFE_DOMAIN=true \
            -p 1200:1200 \
            rsshub:latest

      - name: Fetch affected routes
        id: fetch-route
        uses: actions/github-script@v7
        env:
          EVENT: ${{ toJson(github.event) }}
        with:
          script: |
            const event = JSON.parse(process.env.EVENT)
            const body = event.comment.body
            const number = event.issue.number
            const sender = event.comment.user.login
            const { default: identify } = await import('${{ github.workspace }}/scripts/workflow/test-route/identify.mjs')
            return identify({ github, context, core }, body, number, sender)

      - name: Build RSSHub (for non-PR)
        if: env.TEST_CONTINUE && steps.check-pr.outputs.is_pr == 'false'
        run: pnpm build

      - name: Start RSSHub (for non-PR)
        if: env.TEST_CONTINUE && steps.check-pr.outputs.is_pr == 'false'
        run: pnpm start &
        env:
          ALLOW_USER_HOTLINK_TEMPLATE: true
          ALLOW_USER_SUPPLY_UNSAFE_DOMAIN: true
          NODE_ENV: dev
          LOGGER_LEVEL: debug

      - name: Generate feedback
        if: env.TEST_CONTINUE
        uses: actions/github-script@v7
        env:
          TEST_BASEURL: http://localhost:1200
          TEST_ROUTES: ${{ steps.fetch-route.outputs.result }}
          EVENT: ${{ toJson(github.event) }}
          PULL_REQUEST: ${{ steps.pr-data.outputs.data }}
        with:
          script: |
            const event = JSON.parse(process.env.EVENT)
            const PR = JSON.parse(process.env.PULL_REQUEST)
            const link = process.env.TEST_BASEURL
            const routes = JSON.parse(process.env.TEST_ROUTES)
            const number = PR.number
            core.info(`${link}, ${routes}, ${number}`)

            const { execSync } = require('child_process');
            execSync('npm install js-beautify', { stdio: 'inherit' });

            const { default: test } = await import('${{ github.workspace }}/scripts/workflow/test-route/test.mjs')
            await test({ github, context, core }, link, routes, number)

      - name: Print logs (for non-PR)
        if: env.TEST_CONTINUE && steps.check-pr.outputs.is_pr == 'false'
        run: cat ${{ github.workspace }}/logs/combined.log

      - name: Print Docker container logs (for PR)
        if: env.TEST_CONTINUE && steps.check-pr.outputs.is_pr == 'true'
        run: docker logs rsshub

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: logs
          retention-days: 1
